spring:
  application:
    name: zuul
    
server :
  port : 8011

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/ 
  
