spring:
  datasource:
      url: jdbc:mysql://localhost:3306/florida
      username: root
      password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:    
         ddl-auto : update
		 
       
      
